name: Push Develop Branch

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 🏃‍➡️
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Push alkong repo 🚀
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
        with:
          source-directory: .
          destination-github-username: AlkongDalkong
          target-branch: develop
          destination-repository-name: alkong-dalkong_fe
          user-email: alkongd29@gmail.com
