name: Push Develop Branch ⭐️

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  contents: write
  actions: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 🏃‍➡️
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Git User 🧑‍💻
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Add remote repository 🌐
        run: git remote add target https://${{ secrets.PUSH_TOKEN }}@github.com/AlkongDalkong/alkong-dalkong_fe.git

      - name: Push develop to develop 🚀
        run: git push target develop:develop
