name: Push Develop Branch 🔨

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 🏃‍➡️
        uses: actions/checkout@v2

      - name: Set up Git User 🧑‍💻
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Push to destination repo 🚀
        run: git push https://${{ secrets.PUSH_TOKEN }}@github.com/AlkongDalkong/alkong-dalkong_fe.git develop:develop
