name: Push Main Branch 🏠

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 🏃‍➡️
        uses: actions/checkout@v2

      - name: Set up Git User 🧑‍💻
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Push main to main 🚀
        run: git push https://${{ secrets.PUSH_TOKEN }}@github.com/AlkongDalkong/alkong-dalkong_fe.git main:main
